-- =============================================================================
-- TruthGuard AI — Supabase schema, RLS policies and signup trigger
-- Part B.1 (schema) · Part B.2 (RLS) · Part B.3 (auth trigger) · Part C.6 (audit)
-- =============================================================================
-- HOW TO RUN:  Supabase Dashboard → SQL Editor → New query → paste this whole
--              file → Run. It is idempotent-ish: sections use IF NOT EXISTS /
--              DROP POLICY IF EXISTS so re-running is safe.
--
-- SECURITY MODEL IN ONE PARAGRAPH (for the report):
--   The Supabase ANON key is public, so the browser can talk to Postgres
--   directly. That is only safe because Row Level Security rewrites every query
--   with a predicate derived from the caller's JWT (`auth.uid()`, `auth.jwt()`).
--   A student physically cannot SELECT another student's scan_logs — not because
--   the React app hides it, but because the rows are filtered inside the
--   database engine before they ever reach the network. Policies therefore fail
--   CLOSED: with no matching policy, the answer is an empty set, never an error
--   that leaks existence, and never the data.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 0. EXTENSIONS
-- -----------------------------------------------------------------------------
create extension if not exists "pgcrypto";   -- gen_random_uuid()
-- Note: emails are stored as plain `text` and lower-cased by the client
-- (AuthContext/Signup) before signUp. citext would also work on Supabase, but
-- avoiding the extension keeps the schema portable and removes one dependency.


-- -----------------------------------------------------------------------------
-- 1. ROLE ENUM
--    A Postgres enum (rather than free text) means an invalid role such as
--    'admin' or "student'; drop table profiles; --" cannot be stored at all.
--    This is input validation at the storage layer — the strongest kind.
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type public.user_role as enum ('student', 'educator');
  end if;
end $$;


-- -----------------------------------------------------------------------------
-- 2. PROFILES  (public profile / role row, 1:1 with auth.users)
-- -----------------------------------------------------------------------------
create table if not exists public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  email       text,
  role        public.user_role not null default 'student',  -- LEAST PRIVILEGE default
  role_locked boolean not null default false,               -- set true after first assignment
  created_at  timestamptz not null default now()
);

comment on table  public.profiles is
  'One row per auth.users row. Holds the RBAC role used by RLS policies and the Educator Dashboard.';
comment on column public.profiles.role_locked is
  'Write-once guard: after the signup flow sets the role, further client-side role changes are rejected by the enforce_role_immutable trigger. Prevents self-service privilege escalation.';

create index if not exists profiles_role_idx on public.profiles (role);


-- -----------------------------------------------------------------------------
-- 3. SCAN_LOGS  (the audit trail + dashboard analytics source)
--
--    SECURITY FEATURE: AUDIT TRAIL (Part C.6)
--    Each row answers WHO / WHAT / RESULT / WHEN for every AI call:
--      who    -> user_id (FK to auth.users, immutable identity)
--      what   -> content_type + input_summary (truncated; we never store raw
--                image bytes, only the filename, which limits data exposure)
--      result -> verdict + confidence_score
--      when   -> timestamp, DEFAULT now(), generated BY THE DATABASE.
--    The timestamp being server-generated matters: a client could otherwise
--    back-date or forward-date its own activity and corrupt the audit record.
--    There is deliberately NO update and NO delete policy, so once written a log
--    line cannot be edited or erased by any application user — append-only.
-- -----------------------------------------------------------------------------
create table if not exists public.scan_logs (
  id               bigint generated always as identity primary key,
  -- nullable + ON DELETE SET NULL: deleting a user must NOT delete audit history.
  user_id          uuid references auth.users (id) on delete set null,
  content_type     text not null check (content_type in ('image', 'text')),
  input_summary    text,
  verdict          text,
  confidence_score numeric(5,2) check (confidence_score is null
                                       or (confidence_score >= 0 and confidence_score <= 100)),
  timestamp        timestamptz not null default now()
);

comment on table public.scan_logs is
  'Append-only audit log of every detection / fact-check. Powers the Educator Dashboard and abuse review.';

create index if not exists scan_logs_user_time_idx on public.scan_logs (user_id, timestamp desc);
create index if not exists scan_logs_time_idx      on public.scan_logs (timestamp desc);
create index if not exists scan_logs_type_idx      on public.scan_logs (content_type);


-- -----------------------------------------------------------------------------
-- 4. HELPER FUNCTIONS USED BY POLICIES
--
--    SECURITY: both are `stable` + `security definer` with an explicitly pinned
--    search_path. Pinning search_path is important for SECURITY DEFINER
--    functions: without it an attacker who can create objects in an earlier
--    schema could shadow `public.profiles` and hijack the function (a classic
--    Postgres privilege-escalation path flagged by Supabase's own linter).
-- -----------------------------------------------------------------------------

-- Role of the CURRENT caller (from the profiles row, not from a client claim).
create or replace function public.current_user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select role from public.profiles where id = auth.uid();
$$;

-- Role carried inside the JWT's app_metadata (used by the FastAPI middleware,
-- and handy for policies that must work before the profiles row is visible).
create or replace function public.jwt_role()
returns text
language sql
stable
as $$
  select coalesce(
    auth.jwt() -> 'app_metadata' ->> 'role',
    auth.jwt() -> 'user_metadata' ->> 'role'
  );
$$;

grant execute on function public.current_user_role() to authenticated;
grant execute on function public.jwt_role()          to authenticated;


-- -----------------------------------------------------------------------------
-- 5. set_my_role(p_role)  — the ONLY sanctioned way to change your own role
--
--    WHY A FUNCTION INSTEAD OF A PLAIN UPDATE?
--    If Supabase's "Confirm email" is ON, signUp() returns NO session, so the
--    new user has no JWT and the profiles RLS policy correctly rejects their
--    update — leaving every educator permanently stuck as 'student'. This
--    SECURITY DEFINER function solves that, and it is deliberately narrow:
--      * it only ever touches the row where id = auth.uid()  (no other user)
--      * it only works while role_locked = false            (write-once)
--      * it only accepts the two enum values                (no 'admin')
--      * it then sets role_locked = true                    (closes the door)
--    So it grants exactly one bit of privilege, once, to yourself.
-- -----------------------------------------------------------------------------
create or replace function public.set_my_role(p_role text)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid  uuid := auth.uid();
  v_role public.user_role;
begin
  if v_uid is null then
    raise exception 'Not authenticated' using errcode = '42501';
  end if;

  -- Whitelist the input BEFORE casting; never trust a value from the browser.
  if p_role is null or lower(trim(p_role)) not in ('student', 'educator') then
    raise exception 'Invalid role: %', p_role using errcode = '22023';
  end if;
  v_role := lower(trim(p_role))::public.user_role;

  update public.profiles
     set role        = v_role,
         role_locked = true
   where id = v_uid
     and role_locked = false;

  return found;
end;
$$;

-- Executable by a signed-in user only. The function itself re-checks auth.uid()
-- and raises 42501 if the caller is anonymous, so this grant is defence in depth.
grant execute on function public.set_my_role(text) to authenticated;


-- -----------------------------------------------------------------------------
-- 6. handle_new_user()  — trigger that creates the profiles row on signup
--    Part B.3. Fires AFTER INSERT on auth.users, so an account can never exist
--    without a profile (which would leave it role-less and locked out of
--    everything — a fail-closed outcome, but a confusing one).
-- -----------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_role public.user_role;
begin
  -- Prefer the role the client sent in signUp({ options: { data: { role } } }),
  -- fall back to anything in app_metadata, otherwise DEFAULT TO STUDENT.
  -- SECURITY: least privilege. If the input is missing, malformed or an
  -- unexpected string, the user gets the *lowest* role, never the highest.
  begin
    v_role := coalesce(
      nullif(new.raw_user_meta_data ->> 'role', ''),
      nullif(new.raw_app_meta_data  ->> 'role', ''),
      'student'
    )::public.user_role;
  exception when others then
    v_role := 'student';   -- invalid enum text -> downgrade, do not fail signup
  end;

  insert into public.profiles (id, email, role, role_locked)
  values (new.id, new.email, v_role, false)
  on conflict (id) do update
     set email = excluded.email,
         -- never UPGRADE an existing profile silently; keep the stored role
         role  = public.profiles.role;

  -- Mirror the role into the JWT claims so the FastAPI backend can do a
  -- cheap role check without a database round-trip (Part C.7 layer 3).
  new.raw_app_meta_data :=
    coalesce(new.raw_app_meta_data, '{}'::jsonb) || jsonb_build_object('role', v_role::text);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- -----------------------------------------------------------------------------
-- 7. enforce_role_immutable()  — blocks self-service privilege escalation
--    Without this, a student could PATCH their own profiles row
--    (`supabase.from('profiles').update({ role: 'educator' })`) because the RLS
--    policy legitimately allows updating your own row. This trigger ignores any
--    role/role_locked change coming from a normal authenticated session.
--    Role changes must be made by a service/admin (Dashboard, service_role key,
--    or a signed-in postgres session), which bypasses RLS + this guard.
-- -----------------------------------------------------------------------------
create or replace function public.enforce_role_immutable()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is not null and auth.uid() = new.id then
    new.role        := old.role;         -- silently revert
    new.role_locked := old.role_locked;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_enforce_role on public.profiles;
create trigger profiles_enforce_role
  before update on public.profiles
  for each row execute function public.enforce_role_immutable();


-- -----------------------------------------------------------------------------
-- 8. ROW LEVEL SECURITY — enable
--    SECURITY: enabling RLS with NO policies = deny all. That is the safe
--    starting point; we then open exactly the access we need, per role.
--    (Also enable on profiles; without it, policies are ignored entirely.)
-- -----------------------------------------------------------------------------
alter table public.profiles  enable row level security;
alter table public.scan_logs enable row level security;

-- Belt and braces: even the table owner is subject to RLS. Supabase roles
-- normally are, but stating it makes the guarantee explicit and survives a
-- migration that changes ownership.
alter table public.profiles  force row level security;
alter table public.scan_logs force row level security;


-- -----------------------------------------------------------------------------
-- 9. RLS POLICIES — PROFILES  (Part B.2 bullet 3)
--    "Users can only read/update their own profile row."
-- -----------------------------------------------------------------------------
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  to authenticated
  using (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  to authenticated
  using (id = auth.uid())          -- which existing rows may be modified
  with check (id = auth.uid());    -- and what they may be modified INTO
                                   -- (stops re-pointing a row at another user id)

-- (b) EDUCATORS may read all profile rows.
--     WHY THIS POLICY IS NECESSARY (easy to miss!):
--       The dashboard view `educator_scan_logs` LEFT JOINs profiles to resolve
--       "submitted by". That view is security_invoker, so it runs with the
--       caller's rights and the profiles SELECT policies apply to the join.
--       Without this policy an educator would see every scan row but a NULL
--       email for anyone except themselves — a silent, confusing data gap.
--     DATA-MINIMISATION: this exposes only (id, email, role, created_at) of
--       users in the same project, to an authenticated educator, for the
--       explicit purpose of attribution. It does NOT expose auth.users, the
--       password hash, or any confirmation token, and the UI masks emails on
--       screen because dashboards get projected in classrooms.
--     NO RECURSION: current_user_role() is SECURITY DEFINER, so resolving the
--       caller's role never re-enters these policies.
drop policy if exists "educators_select_all_profiles" on public.profiles;
create policy "educators_select_all_profiles"
  on public.profiles for select
  to authenticated
  using (public.current_user_role() = 'educator');

-- No INSERT policy for clients on purpose: profile rows are created only by the
-- handle_new_user() trigger (SECURITY DEFINER), so a user cannot fabricate a
-- profile for an arbitrary id.
-- No DELETE policy: profiles die with the auth.users row (ON DELETE CASCADE).


-- -----------------------------------------------------------------------------
-- 10. RLS POLICIES — SCAN_LOGS  (Part B.2 bullets 1 & 2)
-- -----------------------------------------------------------------------------

-- (a) STUDENTS: see ONLY their own logs.
drop policy if exists "students_select_own_scan_logs" on public.scan_logs;
create policy "students_select_own_scan_logs"
  on public.scan_logs for select
  to authenticated
  using (
    user_id = auth.uid()
    and coalesce(public.current_user_role(), 'student') = 'student'
  );

-- (b) ANY authenticated user may INSERT a log for themselves only.
--     `with check (user_id = auth.uid())` is the critical half: it stops a user
--     from writing an audit entry attributed to somebody else (which would be
--     both a data-integrity attack and a way to frame another student).
drop policy if exists "users_insert_own_scan_logs" on public.scan_logs;
create policy "users_insert_own_scan_logs"
  on public.scan_logs for insert
  to authenticated
  with check (user_id = auth.uid());

-- (c) EDUCATORS: see ALL logs (analytics), for any time range.
drop policy if exists "educators_select_all_scan_logs" on public.scan_logs;
create policy "educators_select_all_scan_logs"
  on public.scan_logs for select
  to authenticated
  using (public.current_user_role() = 'educator');

-- (d) NOBODY may UPDATE or DELETE scan logs.
--     We simply do not create such policies. With RLS enabled and forced, the
--     absence of a policy is a hard deny — this is what makes the log an
--     append-only AUDIT TRAIL rather than an editable table (Part C.6).


-- -----------------------------------------------------------------------------
-- 11. VIEW FOR THE EDUCATOR DASHBOARD
--     Joins scan_logs -> profiles -> auth.users so the dashboard can show
--     "submitted by" without N+1 queries from the browser.
--
--     SECURITY: `security_invoker = true` (Postgres 15+, which Supabase runs)
--     means the view executes with the CALLER's rights, so the underlying RLS
--     policies still apply. A student querying this view gets only their own
--     rows; an educator gets everything. Without that option a view would run as
--     its owner and silently bypass RLS — a very common Supabase security bug.
-- -----------------------------------------------------------------------------
drop view if exists public.educator_scan_logs;
create view public.educator_scan_logs
with (security_invoker = true)
as
select
  sl.id,
  sl.user_id,
  sl.content_type,
  sl.input_summary,
  sl.verdict,
  sl.confidence_score,
  sl.timestamp,
  p.role  as user_role,
  u.email as user_email
from public.scan_logs sl
left join public.profiles  p on p.id = sl.user_id
left join auth.users       u on u.id = sl.user_id;

comment on view public.educator_scan_logs is
  'Dashboard feed. security_invoker=true, so RLS on scan_logs/profiles still governs what each caller sees.';

-- Only signed-in users may query it; the public/anon role gets nothing.
revoke all on public.educator_scan_logs from public, anon;
grant select on public.educator_scan_logs to authenticated;


-- -----------------------------------------------------------------------------
-- 12. TABLE PRIVILEGES (least privilege for the anon role)
-- -----------------------------------------------------------------------------
revoke all on public.profiles, public.scan_logs from anon;
grant usage on schema public to authenticated, anon;
grant select, insert, update on public.profiles  to authenticated;
grant select, insert         on public.scan_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;


-- -----------------------------------------------------------------------------
-- 13. OPTIONAL: DEMO SEED DATA
--     The Educator Dashboard looks empty on a fresh project. Uncomment the block
--     below AFTER creating two test accounts (an educator + a student) and
--     replacing the emails, then run it once. Do not ship seeded data to prod.
-- -----------------------------------------------------------------------------
-- with edu as (select id from auth.users where email = 'educator@college.edu' limit 1),
--      stu as (select id from auth.users where email = 'student@college.edu'  limit 1)
-- insert into public.scan_logs (user_id, content_type, input_summary, verdict, confidence_score, timestamp)
-- values
--   ((select id from stu), 'image', 'politician_speech_screenshot.png', 'Likely Fake', 94.20, now() - interval '1 day'),
--   ((select id from stu), 'text',  'Vaccines cause autism according to a 1998 study', 'False', 92.00, now() - interval '2 days'),
--   ((select id from stu), 'image', 'family_photo_2019.jpg',              'Likely Real', 88.10, now() - interval '2 days'),
--   ((select id from edu), 'image', 'news_anchor_clip_frame.png',         'Uncertain',   52.75, now() - interval '3 hours'),
--   ((select id from edu), 'text',  'The Eiffel Tower was built in 1889', 'True',        90.00, now() - interval '4 hours');


-- =============================================================================
-- DONE. Verify with:
--   select count(*) from public.profiles;
--   select * from public.scan_logs limit 5;
--   select polname, polcmd from pg_policy where polrelid = 'public.scan_logs'::regclass;
-- Then follow docs/TESTING_CHECKLIST.md to prove the policies actually work.
-- =============================================================================
