import { supabase } from './supabaseClient.js'
import { truncate } from '../utils/validation.js'

/**
 * ---------------------------------------------------------------------------
 * scanLog.js — writes every successful AI analysis into Supabase `scan_logs`
 * ---------------------------------------------------------------------------
 * SECURITY FEATURE: AUDIT TRAIL (Part C.6)
 *   Each row records WHO (user_id, an immutable reference to auth.users),
 *   WHAT (content_type + input_summary), the OUTCOME (verdict + confidence) and
 *   WHEN (timestamp, generated by the database, not by the client — so a
 *   malicious user cannot back-date their own activity).
 *   That is exactly what an audit log needs: a tamper-evident, attributable
 *   record of every privileged/expensive action taken on the platform.
 *   It also doubles as the analytics source for the Educator Dashboard, and as
 *   an abuse-detection signal (one account submitting 500 images/hour is visible
 *   in a single query).
 *
 * WHY THE INSERT IS CLIENT-SIDE BUT STILL SAFE:
 *   The insert runs with the user's own JWT and Row Level Security allows a
 *   student to insert ONLY rows where user_id = auth.uid(). A user cannot write
 *   a log line attributed to somebody else, and cannot UPDATE or DELETE history
 *   (no policy grants it). The database, not the browser, enforces this.
 *
 * FAILURE IS NON-FATAL BY DESIGN:
 *   If logging fails we must not throw away a perfectly good AI result the user
 *   already paid ~3 seconds of GPU time for. We warn in the console and continue.
 */

export async function logScan({ contentType, inputSummary, verdict, confidenceScore, userId }) {
  const row = {
    user_id: userId ?? null,
    content_type: contentType, // 'image' | 'text'
    input_summary: truncate(inputSummary, 180),
    verdict: truncate(verdict, 40),
    confidence_score:
      typeof confidenceScore === 'number' && Number.isFinite(confidenceScore)
        ? Math.max(0, Math.min(100, Number(confidenceScore.toFixed(2))))
        : null,
    // `timestamp` intentionally omitted -> DB default now().
  }

  try {
    const { error } = await supabase.from('scan_logs').insert(row)
    if (error) {
      // Most likely cause in dev: the schema/RLS script hasn't been run yet, or
      // user_id is null because the profile row doesn't exist.
      // eslint-disable-next-line no-console
      console.warn('[TruthGuard] audit log insert failed:', error.message)
      return { ok: false, error }
    }
    return { ok: true }
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn('[TruthGuard] audit log insert threw:', err?.message)
    return { ok: false, error: err }
  }
}

/**
 * Aggregate stats for the Educator Dashboard (Part A.4 / Part B.5).
 *
 * SECURITY: this query is made with the logged-in user's JWT. The RLS policy
 * `educators_select_all_scan_logs` only matches when the caller's profile.role =
 * 'educator'. If a student calls it, Postgres simply returns zero rows — the
 * query is not "blocked", it is filtered. That is the important property of RLS:
 * there is no code path in the frontend that can widen the result set, because
 * the filtering happens inside the database engine.
 */
export async function fetchEducatorStats({ days = 7, limit = 25 } = {}) {
  const EMPTY = {
    rows: [],
    totals: {
      totalScans: 0,
      deepfakesDetected: 0,
      imageScans: 0,
      textChecks: 0,
      avgConfidence: 0,
      uniqueUsers: 0,
    },
    recentFlagged: [],
  }

  const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString()

  // SECURITY (defence in depth, layer 1b):
  //   We re-check the caller's role here, inside the data service, instead of
  //   trusting only that <EducatorRoute> guarded the page. If a student forced
  //   this component to mount (DevTools), this returns an empty result set
  //   without even issuing the query.
  //   The AUTHORITATIVE control is still PostgreSQL RLS: even if this check were
  //   deleted, `educators_select_all_scan_logs` would filter out everyone else's
  //   rows and `students_select_own_scan_logs` would return only their own.
  //   Layered checks = a bug in one layer does not become a data breach.
  if (supabase.__demo !== true) {
    const { data: me } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', (await supabase.auth.getUser()).data?.user?.id)
      .maybeSingle()
    if (me?.role !== 'educator') return EMPTY
  }

  const { data, error } = await supabase
    // Explicit column list (not '*'): if the view ever changes, this fails loudly
    // at the query instead of silently rendering undefined cells.
    .from('educator_scan_logs')
    .select(
      'id, user_id, content_type, input_summary, verdict, confidence_score, timestamp, user_role, user_email',
    )
    .gte('timestamp', since)
    .order('timestamp', { ascending: false })
    .limit(500)

  if (error) throw error

  const rows = data ?? []
  if (rows.length === 0) return EMPTY

  const withScore = rows.filter((r) => typeof r.confidence_score === 'number')
  const flagged = rows.filter(isFlagged)

  return {
    rows,
    totals: {
      totalScans: rows.length,
      deepfakesDetected: flagged.length,
      imageScans: rows.filter((r) => r.content_type === 'image').length,
      textChecks: rows.filter((r) => r.content_type === 'text').length,
      avgConfidence: withScore.length
        ? withScore.reduce((sum, r) => sum + r.confidence_score, 0) / withScore.length
        : 0,
      uniqueUsers: new Set(rows.map((r) => r.user_id).filter(Boolean)).size,
    },
    recentFlagged: flagged.slice(0, limit),
  }
}

/** "Flagged" = the model thinks the content is fake / the claim is false. */
export function isFlagged(row) {
  const v = String(row?.verdict ?? '').toLowerCase()
  return v.includes('fake') || v === 'false' || v.includes('misleading')
}
