#!/usr/bin/env python3
"""
=============================================================================
mock_backend.py — a contract-accurate stand-in for the real AI backend
=============================================================================
Standard library ONLY. No pip install. Python 3.8+.

    python tools/mock_backend.py                 # http://127.0.0.1:8000
    python tools/mock_backend.py --port 8001
    python tools/mock_backend.py --latency 1.5   # slower, for loading-state demos

Then point the frontend at it:  frontend/.env
    VITE_API_BASE_URL=http://127.0.0.1:8000
    VITE_DEMO_MODE=true
and restart `npm run dev`.

WHY THIS EXISTS
    Your detection UI, verdict flip, confidence ring, audit logging, rate-limit
    cooldown and error mapping can all be developed and DEMONDED without waiting
    on a GPU, a Hugging Face Space, or a teammate. It implements the exact
    response contract from the project brief:

      POST /api/v1/detect-image  multipart field "file", <=8MB
        -> {verdict, confidence, raw_label, fake_probability, is_fake, analyzed_in_ms}
      POST /api/v1/fact-check    {"claim": "..."} 10-1000 chars
        -> {verdict, explanation, sources, retrieved_context, checked_in_ms}
      GET  /health               -> {status, services}
      errors                     -> {"detail": ..., "error_code": ...}
                                   with 400/413/422/429/415

    It also enforces the same validation the real backend should (MIME type,
    8 MB ceiling, claim length) and the same CORS shape, so a frontend that
    works against this will work against the real one.

    EXTRA: send the header `X-Mock-Status: 429` (or 502, 503, 504, 413) to make
    it return that error on purpose — that is how you demo the rate-limit
    cooldown and the friendly error messages without breaking anything.

    There is a built-in rate limiter: more than 6 AI calls in 10 seconds returns
    429, so you can demo Part C.3 by simply clicking fast.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  THIS IS NOT A DEEPFAKE DETECTOR. It contains no model. Verdicts are      !!
!!  derived from the file's bytes/name and from keyword matching. Every      !!
!!  response carries "_mock": true and "_disclaimer". Never present this as  !!
!!  real detection — use it to demo the INTERFACE, then swap in the real URL. !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================================
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import threading
import time
from collections import deque
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

DISCLAIMER = (
    "MOCK BACKEND: no model is running. This verdict was generated by a stub for "
    "interface testing and must not be presented as real deepfake detection."
)

# ---------------------------------------------------------------------------
# Deterministic pseudo-detection
# ---------------------------------------------------------------------------
def verdict_from_bytes(data: bytes, filename: str) -> dict:
    """
    Produce a stable, plausible verdict from the upload.

    Deterministic on purpose: the same image always gives the same answer, so a
    demo is repeatable. Three signals, in order of weight:
      1. filename keywords  ('deepfake', 'fake', 'ai', 'generated', 'real', ...)
      2. a hash of the bytes -> a stable pseudo-probability
      3. PNG vs JPEG (real photos are usually JPEG; PNGs are often screenshots or
         generated exports) -> a small nudge
    """
    name = (filename or "").lower()
    p = None

    if any(k in name for k in ("deepfake", "fake", "generated", "aigen", "ai-gen", "synthetic", "gan")):
        p = 0.88 + (int(hashlib.sha256(data).hexdigest(), 16) % 100) / 1000.0
    elif any(k in name for k in ("real", "authentic", "original", "family", "photo", "selfie")):
        p = 0.04 + (int(hashlib.sha256(data).hexdigest(), 16) % 80) / 1000.0
    else:
        h = int(hashlib.sha256(data).hexdigest(), 16)
        p = (h % 1000) / 1000.0            # 0.000 – 0.999, stable per file
        if data[:8] == b"\x89PNG\r\n\x1a\n":
            p = min(0.999, p * 0.7 + 0.22)  # PNG nudge
        p = round(p, 3)

    p = max(0.001, min(0.999, p))

    if p >= 0.80:
        verdict, label, is_fake = "Likely Fake", "fake", True
    elif p <= 0.25:
        verdict, label, is_fake = "Likely Real", "real", False
    else:
        verdict, label, is_fake = "Uncertain", "uncertain", False

    # Confidence = how far from the 50/50 boundary, expressed 0-100.
    confidence = round(50 + abs(p - 0.5) * 100, 1)

    return {
        "verdict": verdict,
        "confidence": confidence,
        "raw_label": label,
        "fake_probability": round(p, 3),
        "is_fake": is_fake,
    }


# A tiny knowledge base so the fact-checker gives sensible, varied answers.
CLAIMS = [
    {
        "match": r"vaccin|autism|mmr",
        "verdict": "False",
        "explanation": (
            "The claim traces back to a 1998 Lancet paper by Andrew Wakefield studying 12 children. "
            "That paper was fully retracted in 2010 after an investigation found falsified data and "
            "undisclosed financial conflicts of interest; Wakefield lost his medical licence. Since "
            "then, studies covering well over a million children have found no link between vaccines "
            "and autism."
        ),
        "sources": [
            "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(10)60175-4/fulltext",
            "https://www.cdc.gov/vaccinesafety/concerns/autism.html",
            "https://www.who.int/news-room/questions-and-answers/item/vaccines-and-immunization-what-is-vaccination",
        ],
    },
    {
        "match": r"eiffel|1889|world fair|exposition",
        "verdict": "True",
        "explanation": (
            "The Eiffel Tower was completed in 1889 and served as the entrance arch to the Exposition "
            "Universelle, the world's fair held in Paris to mark the centenary of the French Revolution. "
            "It was designed by Gustave Eiffel's engineering company and was intended to be dismantled "
            "after 20 years; it survived because it proved invaluable as a radio transmission mast."
        ),
        "sources": [
            "https://www.britannica.com/topic/Eiffel-Tower-Paris-France",
            "https://www.toureiffel.paris/en/the-monument/history",
        ],
    },
    {
        "match": r"garlic|cure|remedy|herbal|homeopath",
        "verdict": "False",
        "explanation": (
            "No food or household remedy cures a viral infection. Garlic has some documented "
            "antimicrobial properties in laboratory settings, but that is not the same as treating an "
            "infection in a human body. Viral infections are managed by the immune system, antivirals "
            "where they exist, and supportive care; relying on a kitchen remedy can delay effective "
            "treatment."
        ),
        "sources": [
            "https://www.who.int/news-room/questions-and-answers/item/coronavirus-disease-(covid-19)-food-safety-and-nutrition",
            "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7025063/",
        ],
    },
    {
        "match": r"mail.*vot|vot.*mail|postal.*vot|election fraud|ballot",
        "verdict": "False",
        "explanation": (
            "Extensive research and audits find no evidence that voting by mail meaningfully increases "
            "election fraud. Fraud of any kind is rare in jurisdictions with postal voting; documented "
            "cases number in the tens out of hundreds of millions of ballots. Mail-in voting does add "
            "procedural complexity — signature verification, postmark deadlines — which can slow "
            "counting, and slower counting is often mistaken for manipulation."
        ),
        "sources": [
            "https://www.brennancenter.org/our-work/research-reports/mail-voting-what-myths-and-real",
            "https://apnews.com/article/elections-voting-fraud-claims-fact-check",
        ],
    },
    {
        "match": r"flat earth|round earth|earth is flat",
        "verdict": "False",
        "explanation": (
            "Earth is an oblate spheroid. This is established by centuries of independent evidence: "
            "ships disappearing hull-first over the horizon, different constellations at different "
            "latitudes, Eratosthenes' shadow measurement around 240 BC, circumnavigation, GPS and "
            "satellite operation, and direct imagery from orbit and deep space."
        ),
        "sources": [
            "https://www.nasa.gov/missions/goddard/earth-is-a-ball-but-not-a-perfect-one/",
            "https://www.scientificamerican.com/article/why-is-earth-round/",
        ],
    },
]

DEFAULT_CLAIM = {
    "verdict": "Unverified",
    "explanation": (
        "I could not find retrieved evidence that either supports or refutes this claim with "
        "sufficient confidence. That is itself a useful result: an unverified claim is not a false "
        "one, and it is not a reason to share it. Try rephrasing it as a single checkable statement, "
        "or search the primary sources directly."
    ),
    "sources": [
        "https://www.snopes.com/",
        "https://fullfact.org/",
        "https://www.factcheck.org/",
    ],
}


def check_claim(claim: str) -> dict:
    low = claim.lower()
    for entry in CLAIMS:
        if re.search(entry["match"], low):
            return {
                "verdict": entry["verdict"],
                "explanation": entry["explanation"],
                "sources": entry["sources"],
            }
    return {
        "verdict": DEFAULT_CLAIM["verdict"],
        "explanation": DEFAULT_CLAIM["explanation"],
        "sources": DEFAULT_CLAIM["sources"]
        + [f"https://duckduckgo.com/?q={re.sub(r'[^A-Za-z0-9]+', '+', claim).strip('+')[:80]}",],
    }


# ---------------------------------------------------------------------------
# Rate limiter (so you can demo the Part C.3 cooldown)
# ---------------------------------------------------------------------------
class RateLimiter:
    def __init__(self, limit: int, window: float):
        self.limit, self.window = limit, window
        self.hits: deque[float] = deque()
        self.lock = threading.Lock()

    def allow(self) -> tuple[bool, int]:
        now = time.time()
        with self.lock:
            while self.hits and now - self.hits[0] > self.window:
                self.hits.popleft()
            if len(self.hits) >= self.limit:
                return False, int(self.window - (now - self.hits[0])) + 1
            self.hits.append(now)
            return True, 0


LIMITER = RateLimiter(limit=6, window=10.0)

# ---------------------------------------------------------------------------
# Multipart parsing (only what we need: pull out the first file part)
# ---------------------------------------------------------------------------
def parse_multipart(body: bytes, content_type: str) -> tuple[bytes, str, str]:
    m = re.search(r'boundary="?([^";]+)"?', content_type)
    if not m:
        return b"", "", ""
    boundary = ("--" + m.group(1)).encode()
    for part in body.split(boundary):
        part = part.strip(b"\r\n")
        if not part or part == b"--":
            continue
        head, _, payload = part.partition(b"\r\n\r\n")
        header_text = head.decode("utf-8", "replace")
        if 'name="file"' not in header_text:
            continue
        fn = re.search(r'filename="([^"]*)"', header_text)
        ct = re.search(r"Content-Type:\s*([^\r\n;]+)", header_text, re.I)
        return payload, (fn.group(1) if fn else "upload"), (ct.group(1) if ct else "")
    return b"", "", ""


MAX_IMAGE_BYTES = 8 * 1024 * 1024
ALLOWED_TYPES = {"image/jpeg", "image/png", "image/webp"}

CONFIG = {"latency": 1.0, "origin": "*"}


class Handler(BaseHTTPRequestHandler):
    server_version = "TruthGuardMock/1.0"
    protocol_version = "HTTP/1.1"

    # ---- plumbing ---------------------------------------------------------
    def log_message(self, fmt, *a):  # quieter, but still informative
        print(f"  {self.command} {self.path} -> {fmt % a}", flush=True)

    def _cors(self):
        self.send_header("Access-Control-Allow-Origin", CONFIG["origin"])
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Authorization, Content-Type, X-Mock-Status")
        self.send_header("Access-Control-Max-Age", "600")
        self.send_header("Vary", "Origin")

    def _send(self, status: int, payload: dict | str, ctype: str = "application/json"):
        body = payload if isinstance(payload, bytes) else json.dumps(payload).encode()
        self.send_response(status)
        self._cors()
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _error(self, status: int, detail: str, code: str):
        self._send(status, {"detail": detail, "error_code": code})

    def do_OPTIONS(self):
        self.send_response(204)
        self._cors()
        self.send_header("Content-Length", "0")
        self.end_headers()

    # ---- forced-error hook for demoing the frontend's error handling -------
    def _forced_status(self) -> int | None:
        raw = self.headers.get("X-Mock-Status")
        try:
            return int(raw) if raw else None
        except ValueError:
            return None

    FORCED = {
        429: ("Too many requests. Please wait a moment before trying again.", "rate_limited"),
        413: ("Image exceeds the 8 MB limit.", "payload_too_large"),
        502: ("Upstream model gateway error.", "bad_gateway"),
        503: ("Detection service temporarily unavailable.", "service_unavailable"),
        504: ("Model inference timed out.", "gateway_timeout"),
        401: ("Authentication required.", "missing_token"),
    }

    def _maybe_forced(self) -> bool:
        st = self._forced_status()
        if st is None:
            return False
        detail, code = self.FORCED.get(st, (f"Forced mock error {st}.", f"http_{st}"))
        if st == 429:
            self.send_response(st)
            self._cors()
            self.send_header("Retry-After", "10")
            self.send_header("Content-Type", "application/json")
            body = json.dumps({"detail": detail, "error_code": code}).encode()
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        else:
            self._error(st, detail, code)
        return True

    # ---- routes ------------------------------------------------------------
    def do_GET(self):
        if self.path.startswith("/health"):
            self._send(200, {
                "status": "ok",
                "services": {
                    "detection": "mock-ready",
                    "fact_check": "mock-ready",
                    "note": "mock_backend.py — no model is loaded",
                },
            })
            return
        if self.path in ("/", "/docs"):
            self._send(200, MOCK_HTML, "text/html; charset=utf-8")
            return
        self._error(404, "Not found. Try /health, /api/v1/detect-image or /api/v1/fact-check.", "not_found")

    def do_POST(self):
        if self._maybe_forced():
            return

        # ---- rate limit ----
        ok, retry = LIMITER.allow()
        if not ok:
            self.send_response(429)
            self._cors()
            self.send_header("Retry-After", str(retry))
            self.send_header("Content-Type", "application/json")
            body = json.dumps({
                "detail": f"Too many requests. Please wait a moment before trying again ({retry}s).",
                "error_code": "rate_limited",
            }).encode()
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return

        length = int(self.headers.get("Content-Length") or 0)
        body = self.rfile.read(length) if length else b""

        # ---- detect-image ----
        if self.path.startswith("/api/v1/detect-image"):
            ctype = self.headers.get("Content-Type", "")
            if "multipart/form-data" not in ctype:
                return self._error(415, "Expected multipart/form-data with a field named 'file'.",
                                   "unsupported_media_type")

            data, filename, file_ctype = parse_multipart(body, ctype)
            if not data:
                return self._error(422, "No file part named 'file' was found in the request.",
                                   "missing_file_field")
            if file_ctype and file_ctype not in ALLOWED_TYPES:
                return self._error(415, f"Unsupported media type '{file_ctype}'. Allowed: jpg, png, webp.",
                                   "unsupported_media_type")
            if len(data) > MAX_IMAGE_BYTES:
                return self._error(413, "Image exceeds the 8 MB limit.", "payload_too_large")
            if not data:
                return self._error(400, "Uploaded file is empty.", "empty_file")

            started = time.perf_counter()
            time.sleep(CONFIG["latency"] + (len(data) % 700) / 1000.0)  # 1.0 – 1.7 s, looks real
            result = verdict_from_bytes(data, filename)
            result["analyzed_in_ms"] = int((time.perf_counter() - started) * 1000)
            result["_mock"] = True
            result["_disclaimer"] = DISCLAIMER
            print(f"    [mock] file={filename!r} bytes={len(data)} -> {result['verdict']} "
                  f"({result['confidence']}%)", flush=True)
            return self._send(200, result)

        # ---- fact-check ----
        if self.path.startswith("/api/v1/fact-check"):
            ctype = self.headers.get("Content-Type", "")
            if "application/json" not in ctype:
                return self._error(415, "Expected application/json.", "unsupported_media_type")
            try:
                payload = json.loads(body or b"{}")
            except json.JSONDecodeError:
                return self._error(400, "Request body is not valid JSON.", "invalid_json")

            claim = payload.get("claim")
            if not isinstance(claim, str):
                return self._error(422, "Field 'claim' must be a string.", "validation_error")
            claim = claim.strip()
            if len(claim) < 10:
                return self._error(422, f"Claim is too short ({len(claim)} chars); minimum is 10.",
                                   "validation_error")
            if len(claim) > 1000:
                return self._error(422, f"Claim is too long ({len(claim)} chars); maximum is 1000.",
                                   "validation_error")

            started = time.perf_counter()
            time.sleep(CONFIG["latency"] * 1.4)
            out = check_claim(claim)
            out["retrieved_context"] = [
                {"text": f"(mock) retrieved passage matching: {claim[:90]}", "score": 0.87},
                {"text": "(mock) second passage providing corroborating detail.", "score": 0.74},
            ]
            out["checked_in_ms"] = int((time.perf_counter() - started) * 1000)
            out["_mock"] = True
            out["_disclaimer"] = DISCLAIMER
            print(f"    [mock] claim={claim[:60]!r} -> {out['verdict']}", flush=True)
            return self._send(200, out)

        self._error(404, "Unknown endpoint.", "not_found")


MOCK_HTML = """<!doctype html><meta charset="utf-8"><title>TruthGuard MOCK backend</title>
<style>body{background:#0A192F;color:#E6F1FF;font:16px/1.6 system-ui;margin:0;padding:3rem}
code{background:#112240;padding:.15rem .4rem;border-radius:6px;color:#64FFDA}
.warn{background:rgba(255,77,77,.12);border:1px solid rgba(255,77,77,.45);color:#FF4D4D;
padding:1rem 1.2rem;border-radius:10px;margin:1.2rem 0}</style>
<h1>TruthGuard AI — MOCK backend</h1>
<div class="warn"><b>This is not a deepfake detector.</b> No model is loaded. Verdicts come from a
deterministic stub so the interface can be developed and demonstrated offline.</div>
<p>Endpoints: <code>GET /health</code> · <code>POST /api/v1/detect-image</code> ·
<code>POST /api/v1/fact-check</code></p>
<p>Force an error with a header: <code>X-Mock-Status: 429</code> (also 413, 502, 503, 504, 401).</p>
<p>Rate limit: 6 AI calls per 10 seconds, then <code>429</code> — click fast in the UI to demo the cooldown.</p>
<p>Point the frontend here by setting <code>VITE_API_BASE_URL=http://127.0.0.1:8000</code> in
<code>frontend/.env</code>, then restart <code>npm run dev</code>.</p>"""


def main() -> None:
    ap = argparse.ArgumentParser(description="Run the TruthGuard AI mock backend.")
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=8000)
    ap.add_argument("--latency", type=float, default=1.0,
                    help="seconds of simulated inference time (default 1.0)")
    ap.add_argument("--origin", default="*",
                    help="value for Access-Control-Allow-Origin (default '*')")
    args = ap.parse_args()

    CONFIG["latency"] = max(0.0, args.latency)
    CONFIG["origin"] = args.origin

    print(f"""
==============================================================================
  TruthGuard AI — MOCK BACKEND (no model loaded)
==============================================================================
  Listening on      http://{args.host}:{args.port}
  Health            GET  /health
  Detection         POST /api/v1/detect-image   (multipart field "file")
  Fact-check        POST /api/v1/fact-check     (JSON {{"claim": "..."}})
  Simulated latency {CONFIG['latency']}s per call
  Rate limit        6 calls / 10s, then HTTP 429
  Force an error    header  X-Mock-Status: 429 | 413 | 502 | 503 | 504 | 401

  >>> In frontend/.env set:
      VITE_API_BASE_URL=http://{args.host}:{args.port}
      VITE_DEMO_MODE=true
  then restart `npm run dev`.

  !! Verdicts are FAKE — deterministic stubs for interface work only. !!
  Press Ctrl+C to stop.
==============================================================================
""", flush=True)

    try:
        ThreadingHTTPServer((args.host, args.port), Handler).serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.")


if __name__ == "__main__":
    main()
